[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name tail
    Path /var/log/cloud-init-output.log
    Read_from_Head true
    Skip_Long_Lines true
    Tag cloud-init-output
    Key message

[FILTER]
    Name modify
    Match cloud-init-output
    Add Source cloud-init-output
    Add level INFO
    Add logger_name cloud-init-output

[INPUT]
    Name systemd
    Systemd_Filter _SYSTEMD_UNIT=transcription-service-worker.service
    Strip_Underscores true
    Tag application-logs

[FILTER]
    Name record_modifier
    Match application-logs
    Allowlist_key MESSAGE

[FILTER]
    Name modify
    Match application-logs
    Rename MESSAGE message

[FILTER]
    Name parser
    Match application-logs
    Key_Name message
    Parser json

[FILTER]
    Name modify
    Match *
    Add SystemdUnit transcription-service-worker.service
    Add app transcription-service-gpu-worker
    Add aws:autoscaling:groupName transcription-service-gpu-workers-<STAGE>
    Add aws:cloudformation:stack-name transcription-service-<STAGE>
    Add gu:build-tool guardian/actions-riff-raff
    Add gu:repo guardian/transcription-service
    Add gu:riff-raff:project investigations::transcription-service
    Add stack investigations
    Add stage <STAGE>

[FILTER]
    Name aws
    Match *
    imds_version v2
    az true
    ec2_instance_id true
    ami_id true
    vpc_id true

[OUTPUT]
    Name es
    Match *
    Port 443
    tls On
    Host <INVESTIGATIONS_LOGS_ENDPOINT>
    Logstash_Format      On
    Logstash_Prefix      transcription-service-logs
    Logstash_DateFormat  %Y.%m.%d
    Suppress_Type_Name   On
    Generate_ID On
    Retry_Limit False
