// languages supported by whisper.cpp
// copied from
// https://github.com/ggerganov/whisper.cpp/blob/25d313b38b1f562200f915cd5952555613cd0110/whisper.cpp#L251
// and values transformed to title case
export const languageCodeToLanguage = Object.freeze({
	auto: 'Auto-detect language',
	en: 'English',
	zh: 'Chinese',
	de: 'German',
	es: 'Spanish',
	ru: 'Russian',
	ko: 'Korean',
	fr: 'French',
	ja: 'Japanese',
	pt: 'Portuguese',
	tr: 'Turkish',
	pl: 'Polish',
	ca: 'Catalan',
	nl: 'Dutch',
	ar: 'Arabic',
	sv: 'Swedish',
	it: 'Italian',
	id: 'Indonesian',
	hi: 'Hindi',
	fi: 'Finnish',
	vi: 'Vietnamese',
	he: 'Hebrew',
	uk: 'Ukrainian',
	el: 'Greek',
	ms: 'Malay',
	cs: 'Czech',
	ro: 'Romanian',
	da: 'Danish',
	hu: 'Hungarian',
	ta: 'Tamil',
	no: 'Norwegian',
	th: 'Thai',
	ur: 'Urdu',
	hr: 'Croatian',
	bg: 'Bulgarian',
	lt: 'Lithuanian',
	la: 'Latin',
	mi: 'Maori',
	ml: 'Malayalam',
	cy: 'Welsh',
	sk: 'Slovak',
	te: 'Telugu',
	fa: 'Persian',
	lv: 'Latvian',
	bn: 'Bengali',
	sr: 'Serbian',
	az: 'Azerbaijani',
	sl: 'Slovenian',
	kn: 'Kannada',
	et: 'Estonian',
	mk: 'Macedonian',
	br: 'Breton',
	eu: 'Basque',
	is: 'Icelandic',
	hy: 'Armenian',
	ne: 'Nepali',
	mn: 'Mongolian',
	bs: 'Bosnian',
	kk: 'Kazakh',
	sq: 'Albanian',
	sw: 'Swahili',
	gl: 'Galician',
	mr: 'Marathi',
	pa: 'Punjabi',
	si: 'Sinhala',
	km: 'Khmer',
	sn: 'Shona',
	yo: 'Yoruba',
	so: 'Somali',
	af: 'Afrikaans',
	oc: 'Occitan',
	ka: 'Georgian',
	be: 'Belarusian',
	tg: 'Tajik',
	sd: 'Sindhi',
	gu: 'Gujarati',
	am: 'Amharic',
	yi: 'Yiddish',
	lo: 'Lao',
	uz: 'Uzbek',
	fo: 'Faroese',
	ht: 'Haitian Creole',
	ps: 'Pashto',
	tk: 'Turkmen',
	nn: 'Nynorsk',
	mt: 'Maltese',
	sa: 'Sanskrit',
	lb: 'Luxembourgish',
	my: 'Myanmar',
	bo: 'Tibetan',
	tl: 'Tagalog',
	mg: 'Malagasy',
	as: 'Assamese',
	tt: 'Tatar',
	haw: 'Hawaiian',
	ln: 'Lingala',
	ha: 'Hausa',
	ba: 'Bashkir',
	jw: 'Javanese',
	su: 'Sundanese',
	yue: 'Cantonese',
});

type LanguageCodeToLanguage = typeof languageCodeToLanguage;

export type LanguageCode = keyof LanguageCodeToLanguage;

// There doesn't seem to be a way to get the object keys that has a type which
// is an array of a union of string literals rather than an array of strings.
// https://www.charpeni.com/blog/properly-type-object-keys-and-object-entries
export const languageCodes = Object.keys(
	languageCodeToLanguage,
) as unknown as LanguageCode[];
