name: 'CI'
on:
  workflow_dispatch:
  push:
jobs:
  setup:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - uses: guardian/actions-read-private-repos@v0.1.1
        with:
          private-ssh-keys: ${{ secrets.PRIVATE_INFRASTRUCTURE_CONFIG_DEPLOY_KEY }}
      - name: Install dependencies
        run: |
          npm install
  build-package-api-client-update:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: build API
        run: |
          npm run api::build
      - name: build Client
        run: |
          npm run client::build
      - name: Package API/Client
        run: |
          npm run package
  build-package-worker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Package Worker
        run: |
          npm run worker::build
          npm run worker::package
  cdk:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: CDK synth
        run: |
          npm run cdk::build
          npm run cdk::lint
          npm run cdk::synth
  upload-to-riff-raff:
    needs: [build-package-api-client-update, build-package-worker, cdk]
    permissions:
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          configPath: packages/cdk/riff-raff.yaml
          buildNumberOffset: 120
          projectName: investigations::transcription-service
          contentDirectories: |
            cdk.out:
              - packages/cdk/cdk.out/TranscriptionService-CODE.template.json
              - packages/cdk/cdk.out/TranscriptionService-PROD.template.json
            transcription-service-api:
              - target/api.zip
            transcription-service-worker:
              - packages/worker/dist/transcription-service-worker_1.0.0_all.deb
      - name: Upload repository project to riff-raff
        uses: guardian/actions-riff-raff@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          configPath: packages/cdk/riff-raff-repository.yaml
          projectName: investigations::transcription-service-repository
          contentDirectories: |
            cdk.out:
              - packages/cdk/cdk.out/TranscriptionServiceRepository.template.json
