name: Release scala worker-interface2

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/scala-release.yml'
      - 'worker-interface/**'

defaults:
  run:
    shell: bash
    working-directory: ./worker-interface/scala

jobs:
  release:
    uses: guardian/gha-scala-library-release-workflow/.github/workflows/reusable-release.yml@support-non-root-directory
    permissions: { contents: write, pull-requests: write }
    with:
      WORKING_DIRECTORY: './worker-interface/scala'
    secrets:
      SONATYPE_TOKEN: ${{ secrets.AUTOMATED_MAVEN_RELEASE_SONATYPE_TOKEN }}
      PGP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_PGP_SECRET }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.AUTOMATED_MAVEN_RELEASE_GITHUB_APP_PRIVATE_KEY }}
